-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 10:48:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GoldDuck
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GoldDuck
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GoldDuck` DEFAULT CHARACTER SET utf8 ;
USE `GoldDuck` ;

-- -----------------------------------------------------
-- Table `GoldDuck`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GoldDuck`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `alias` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoldDuck`.`ideas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GoldDuck`.`ideas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `body` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_ideas_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_ideas_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `GoldDuck`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GoldDuck`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GoldDuck`.`likes` (
  `users_id` INT NULL,
  `ideas_id` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_ideas_ideas1_idx` (`ideas_id` ASC),
  INDEX `fk_users_has_ideas_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_ideas_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `GoldDuck`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_ideas_ideas1`
    FOREIGN KEY (`ideas_id`)
    REFERENCES `GoldDuck`.`ideas` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
